# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

use_frameworks!

target 'ServiceApi_Example' do
  pod 'ServiceApi/AFN', :path => '../'

  target 'ServiceApi_Tests' do
    inherit! :search_paths

    
  end
end
